### ISSUE TITLE
Document site deployment setup / server configuration / access.

### ISSUE THREAD

**Issue by Zimmi48** [coq/coq.github.io#110]
I'd like this repository to contain a document with all the information needed for a developer to administrate the repository, including how to get ssh access to the new servers.

**Comment by maximedenes** [comment]
Yep, I plan to do it once the thing stabilizes a bit. And even before that, we can define a team of sysadmins to which I'll grant ssh access (now that we can do it :) ).

**Comment by Zimmi48** [comment]
No longer relevant.
