### ISSUE TITLE
stdlib / library duplicate urls

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq.github.io#188]
One of https://coq.inria.fr/library/Coq.Init.Wf.html and https://coq.inria.fr/stdlib/Coq.Init.Wf.html should not exist or should redirect to the other.

**Comment by Zimmi48** [comment]
It seems reasonable to redirect the former to the latter.
However, there's also https://coq.inria.fr/distrib/current/stdlib/Coq.Init.Wf.html. Should we make this the canonical URL and remove the short version? (Same question for https://coq.inria.fr/refman/ vs https://coq.inria.fr/distrib/current/refman/.) Or is there another way of marking two pages as identical but keeping alternative URLs for them?
