### ISSUE TITLE
Hidden doc versions?

### ISSUE THREAD

**Issue by SkySkimmer** [coq/coq.github.io#196]
In https://coq.inria.fr/distrib/ we can see a bunch of versions, but the more recent ones do not appear for some reason (even though eg https://coq.inria.fr/distrib/V8.11.0/stdlib/ exists)

**Comment by Zimmi48** [comment]
Yes, this is normal. The right place to look for recent doc versions is https://coq.github.io/doc/. Everything is explained here: https://github.com/coq/www/issues/111. See in particular https://github.com/coq/www/issues/111#issuecomment-547006032.

**Comment by Zimmi48** [comment]
I guess we can close this because this page (https://coq.inria.fr/distrib/) does not exist anymore and it probably not necessary to revive it.
