### ISSUE TITLE
Old links to library docs are broken

### ISSUE THREAD

**Issue by RalfJung** [coq/coq.github.io#230]
Google search results are full of links like https://coq.inria.fr/library/Coq.Lists.List.html that currently no longer work. It'd be great to get proper redirects for these as right now, finding the right docs can be quite painful.

**Comment by Zimmi48** [comment]
For future reference: if we do fix this issue in a reliable way (including for `/distrib` links), we could revert coq/coq#18108.

**Comment by Zimmi48** [comment]
This was fixed in #232. I'll open a new issue with the list of things remaining to do. If you find more broken links, please contribute to it.
