### ISSUE TITLE
Links with anchors do not redirect properly

### ISSUE THREAD

**Issue by RalfJung** [coq/coq.github.io#235]
coqdoc generates links to URLs like http://coq.inria.fr/distrib/V8.18.0/stdlib//Coq.Init.Datatypes.html#list. However, those URLs do not work properly any more: they do go to the page for `Coq.Init.Datatypes`, but they don't jump to the `#list` definition in that page.

Looks like the redirects for the website transition are not working properly with anchors?

**Comment by brandenburg** [comment]
I'm trying to have this fixed in `coqdoc`: https://github.com/coq/coq/pull/18431

**Comment by RalfJung** [comment]
:+1: on fixing newly generated docs to not rely on the redirects, but given there are already tons of links out there, I don't think think that should be considered as fixing this issue.

**Comment by Zimmi48** [comment]
It seems like the JS code that handles the redirects could be adapted to preserve the anchors. Anyone wants to have a try? (If it has to be me, it will take more than a month before I can fix this, even though it likely is a very easy fix.)

**Comment by brandenburg** [comment]
I wasn't aware it's being handled in JavaScript; I presumed it's a server-side redirect. I can take a look.

**Comment by brandenburg** [comment]
Locally, #236 seems to do the trick.

**Comment by RalfJung** [comment]
Sadly github pages don't allow server-side redirects (IIUC), so a JavaScript hack was needed.
